# Generated by Django 2.2.2 on 2019-06-17 09:42

from django.db import migrations, models
import djangoui.user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190616_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=djangoui.user.models.creaet_image_path),
        ),
    ]
